### PR TITLE
Retrieve the full test plan - testcase-platform.

### PR DESCRIPTION
**Pull request by davidrova**
Right now is retrieving only testcases with one platform.

### CODE REVIEW

**Comment by kinow** [comment]
Hi @davidrova 

The code looks good, but that method is used by the Jenkins TestLink Plug-in.

As I'm planning a release of the Java API this weekend, and possibly a release of the plug-in this semester, I want to spend some more time reviewing it with more calm.

**Comment by davidrova** [comment]
Hi @kinow, 

You are right, Jenkins uses that method. That's why we developed a component and invoke our component instead of using jenkins plugin.

That refactor helps us having the result for each platform; working for two years right now.

Regards,

**Comment by kinow** [comment]
>That refactor helps us having the result for each platform; working for two years right now.

That helps a lot, thanks. Instead of cutting a release and later working on this, let me try to set up a Jenkins instance with the plug-in, try your pull request locally and quickly debug it. Should nothing goes wrong, let's merge and release it :-) :+1:

**Comment by kinow** [comment]
Merged locally and tried to package to create a new version of the Jenkins plug-in for testing. But there are tests failing:

```
<testcase classname="br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestPlan" name="testGetAutomatedTestCasesForTestPlan" time="0.009">
    <failure type="java.lang.NullPointerException">java.lang.NullPointerException
	at br.eti.kinoshita.testlinkjavaapi.util.Util.getTestCase(Util.java:511)
	at br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCasesForTestPlan(TestCaseService.java:313)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.getTestCasesForTestPlan(TestLinkAPI.java:848)
	at br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestPlan.testGetAutomatedTestCasesForTestPlan(TestGetTestCasesForTestPlan.java:59)
</failure>
    <system-err>[main] INFO org.eclipse.jetty.server.Server - jetty-8.0.1.v20110908
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:31984 STARTING
</system-err>
  </testcase>
  <testcase classname="br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestPlan" name="testGetAutomatedTestCasesForTestPlanWithExecutionStatus" time="0.005">
    <failure type="java.lang.NullPointerException">java.lang.NullPointerException
	at br.eti.kinoshita.testlinkjavaapi.util.Util.getTestCase(Util.java:511)
	at br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCasesForTestPlan(TestCaseService.java:313)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.getTestCasesForTestPlan(TestLinkAPI.java:848)
	at br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestPlan.testGetAutomatedTestCasesForTestPlanWithExecutionStatus(TestGetTestCasesForTestPlan.java:77)
</failure>
  </testcase>
  <testcase classname="br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestPlanEmptyResult" name="testGetTestCasesForTestPlan" time="0.004"/>
  <testcase classname="br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestSuite" name="testGetTestCasesForTestSuite" time="0.006">
    <failure type="java.lang.NullPointerException">java.lang.NullPointerException
	at br.eti.kinoshita.testlinkjavaapi.util.Util.getTestCase(Util.java:511)
	at br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCasesForTestSuite(TestCaseService.java:246)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.getTestCasesForTestSuite(TestLinkAPI.java:799)
	at br.eti.kinoshita.testlinkjavaapi.testcase.TestGetTestCasesForTestSuite.testGetTestCasesForTestSuite(TestGetTestCasesForTestSuite.java:53)
</failure>
    <system-err>[main] INFO org.eclipse.jetty.server.Server - jetty-8.0.1.v20110908
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:31984 STARTING
</system-err>
  </testcase>
...
  <testcase classname="br.eti.kinoshita.testlinkjavaapi.testcase.issue3224421.TestIssue3224421" name="testRetrieveTestCaseForBuild" time="0.014">
    <failure type="java.lang.NullPointerException">java.lang.NullPointerException
	at br.eti.kinoshita.testlinkjavaapi.util.Util.getTestCase(Util.java:511)
	at br.eti.kinoshita.testlinkjavaapi.TestCaseService.getTestCasesForTestPlan(TestCaseService.java:313)
	at br.eti.kinoshita.testlinkjavaapi.TestLinkAPI.getTestCasesForTestPlan(TestLinkAPI.java:848)
	at br.eti.kinoshita.testlinkjavaapi.testcase.issue3224421.TestIssue3224421.testRetrieveTestCaseForBuild(TestIssue3224421.java:56)
</failure>
    <system-err>[main] INFO org.eclipse.jetty.server.Server - jetty-8.0.1.v20110908
[main] INFO org.eclipse.jetty.server.AbstractConnector - Started SelectChannelConnector@0.0.0.0:31984 STARTING
</system-err>
  </testcase>
```

So will cut 1.9.14-0 release now, and we can sort out these failing tests another time.

Sorry for not being able to spend more time understanding what's happening in the tests @davidrova 

Bruno

**Comment by kinow** [comment]
Fixed tests in master branch (merged other pull requests and forgot to run the tests).

Created a job in Jenkins, and confirmed that the code in master branch is working (updated a job with the junit test class name strategy).

Now checked out this pull request source code, and am updating Eclipse workspace and re-building the plug-in to use this version of the testlink-java-api.

**Comment by kinow** [comment]
And everything worked fine! Yay.

Merged. Releasing right now 1.9.14-0 to Maven central.

**Comment by davidrova** [comment]
Great!!

On Sun, Apr 10, 2016 at 2:25 AM, Bruno P. Kinoshita <
notifications@github.com> wrote:

> And everything worked fine! Yay.
>
> Merged. Releasing right now 1.9.14-0 to Maven central.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/kinow/testlink-java-api/pull/39#issuecomment-207890444>
>



-- 

Saludos,

---------------------------------
David Rodríguez Vallejo
blog: http://globeros-mtb.blogspot.com

**Pull request merged**
