### PR TITLE
implemented method : assignTestCaseExecutionTask

### PR DESCRIPTION
**Pull request by pozharko**
assignTestCaseExecutionTask method implemented

### CODE REVIEW

**Comment by kinow** [comment]
Hi @pozharko, which version of TestLink are you writing your code against? PR looks good, I just need to resync my repos and see if we can merge and cut a new release by this next week :-) 

Thank you

**Comment by pozharko** [comment]
1.9.13 (Stormbringer)

**Comment by pozharko** [comment]
Hi @kinow, can you merge pull request? It would be cool to remove custom code from my project and just use library method.

**Comment by kinow** [comment]
Hi @pozharko! I don't have a development environment with TL to try it, but looking at your code, it looks good. And looks like this is the method in the API being called: https://github.com/TestLinkOpenSourceTRMS/testlink-code/blob/cc05146911162268d969d03880623cb8d363eb1c/lib/api/xmlrpc/v1/xmlrpc.class.php#L6120

So everything looks good. I'm merging this PR and will cut 1.9.13-0 in the next hours. Tomorrow it should already be available from Maven Central repository. 

Thanks and sorry for the delay.
Bruno

**Comment by pozharko** [comment]
Thank you!

**Pull request merged**
