### PR TITLE
getTestCaseCustomFieldExecutionValue is outdated #113

### PR DESCRIPTION
**Pull request by ranashahan**
In this build following updates are included

1. Changes.xml updated 
2. Fixed getTestCaseCustomFieldExecutionValue 

- Added testplan_id param into TestCaseService.java
- Added testplan_id param into TestLinkAPI.java
- Create java file for testcase custom field execution (TestGetTestCaseCustomFieldExecutionValue.java)
- Create xml file for testcase custom field execution value (tl.getTestCaseCustomFieldExecutionValue.xml)

Regards,
Rana Mansoor

### CODE REVIEW

**Comment by schwarcu** [comment]
@kinow   maybe accept pull request?

**Comment by kinow** [comment]
Oh, missed this one while reviewing the recent pull requests, thanks for the reminder @schwarcu (and sorry for the delay @ranashahan ).

Code looks good, and thanks a ton for including tests @ranashahan . The `changes.xml` normally lists `dev` a developer/maintainer, and contributors' info are in the `due-to` attribute. I'll amend the file after merging it.

There are a few recent changes (all contributions 🎉 thanks all), and I am planning to cut a release soon. I have a bit of spare time, and am coincidentally working on an issue with PHP, so I may be able to prepare a dev environment for TestLink, and finally do some proper testing, triage, and then release a version of the API that has been confirmed to work well with TL.

Otherwise will release a version with the latest TL version, plus the suffix `-1` (or N if we have already a release for that version).

Cheers, and happy holidays
Bruno

**Comment by ranashahan** [comment]
Finally i am glad you guys are happy regarding my work 👍, thank you all.
@kinow let me know if you need more help in your upcoming release (Java Code specific only... i don't have PHP expertise) .

**Comment by kinow** [comment]
Releasing 1.9.17-0. Tested with latest from git master, and the basic functionality of the jenkins plugin was still working - I was really surprised. The plugin uses a few of the methods available in the API. No guarantee that everything is working OK though. Cheers

**Pull request merged**
