### PR TITLE
Get test case attachments for test case version

### PR DESCRIPTION
**Pull request by kaiadelmann**
Added parameter for setting specific version of the testcase to get
attachments for (as introduced in TestLink 1.9.18)

Seems I can't get rid of the merged things from the last pull request (and I can't tell why...). Hope you're able to sort it out anyway - Sorry for the extra work...

Best
Kai

### CODE REVIEW

**Comment by kinow** [comment]
Merged in master. @kaiadelmann I just checked out your branch, and noticed it was behind master. I think for the next pull request, if you re-sync your working copy it should work. What I did was

```bash
git fetch --all
git checkout master
git rebase origin/master
# synced!
```

**Comment by kinow** [comment]
But as GitHub appear to be not recognizing the merge, I'm closing it manually. Build failed in travis due to checkstyle being activated by default there... but I executed all tests locally with no issues. Pushed another commit to disable checkstyle.

**Comment by kinow** [comment]
Many thanks once again @kaiadelmann !

**Comment by kaiadelmann** [comment]
You're very welcome! Sorry for the mess...

Bruno P. Kinoshita <notifications@github.com> schrieb am Di., 23. Okt.
2018, 03:48:

**Pull request closed without merging**
