### PR TITLE
added API function to retrieve a testsuite's attachments

### PR DESCRIPTION
**Pull request by vdwals**
Hi,

I just added a function to retrieve a testsuites attachement to testlink and it was merged. Since I'm using your java API, I enhanced it, too, and wanted to share it with you. Thanks for you great work!

Best Regards
Dennis

### CODE REVIEW

**Comment by kinow** [comment]
Hi @vdwals 

Thanks a ton! I'm waiting for a release of TestLink to check the XML RPC API compatibility (which reminds me that tomorrow I can check if the fix was released, just sent an e-mail to myself to remind me in the morninig :-) )

Looks simple to test, and release it. Mind sharing which version of TestLink you are using, please? That way it will be easier for me to test and release with the appropriate TestLink version (i.e. if you are using 1.9.999, it must be released with 1.9.999-0).

Also, by sending this pull request, lots of users will benefit of your change. It might be "my" API meaning that I created, but nowadays it is a community project, so **our** or **the** API might be a better way to say it :-D Thank **you** for your contribution. Ping me if I take too long to update this regarding the date to release it.

Bruno

**Comment by vdwals** [comment]
Hi @kinow 

It's not yet released, it was merged yesterday on branch 1.9 (https://github.com/TestLinkOpenSourceTRMS/testlink-code) and based on 1.9.16. So I assume it'll be part of 1.9.17?

But I can let you know if it's done.

Regards
Dennis

**Comment by kinow** [comment]
Oh, I believe I was waiting for 1.9.16 (see https://github.com/kinow/testlink-java-api/issues/72). Will cut a release for 1.9.16 in the next days anyway, so we can include your change in a smaller release (good for less chance of introducing bugs).

Ping me whenever it has been released and you have some time for testing. I can stop what I'm doing for a few hours to prepare an alpha jar, and then release it once you confirm it's OK.

**Comment by kinow** [comment]
Hi @vdwals would you be able to update TestLinkMethods.java? Another pull request fixed the formatting mess it was (sorry about that).

I can try to fix it myself when merging, after 1.9.17 is released, but if you could update your pull request for that it would be way easier and less likely that I would mess that too.

Sorry. 

Thank you!
Bruno

**Comment by vdwals** [comment]
Hi,

I pushed my change into the new file.

Regards
Dennis

**Comment by kinow** [comment]
Merged! Did a few minor edits, hence the "Closed" instead of "Merged", but your commit has been included in master @vdwals ! Many thanks! Releasing in a few hours.

**Pull request closed without merging**
